const Moviecards = [
  {
    id: "1",
    MovieCountryYear: "Usa, 2016-Current",
    MovieName: "Stranger Things",
    Moviegenre: "Action, Adventure, Horror",
  },
  {
    id: "2",
    MovieCountryYear: "Usa, 2016-Current",
    MovieName: "Batman Begin",
    Moviegenre: "Action Thriller",
  },
  {
    id: "3",
    MovieCountryYear: "Usa, 2016-Current",
    MovieName: "Spide-Man Into The Spider Verse",
    Moviegenre: "Action Thriller",
  },
  {
    id: "4",
    MovieCountryYear: "Usa, 2020",
    MovieName: "Shang-Chi Legend Of The Ten Rign",
    Moviegenre: "Action",
  },
  {
    id: "5",
    MovieCountryYear: "Usa, 2021",
    MovieName: "Dune",
    Moviegenre: "Action, Thriller",
  },
  {
    id: "6",
    MovieCountryYear: "India, 2020",
    MovieName: "Satyamev Jayate",
    Moviegenre: "Action, Adventure",
  },
  {
    id: "7",
    MovieCountryYear: "ndia, 2018-Current",
    MovieName: "Raees",
    Moviegenre: "Action Thriller",
  },
  {
    id: "8",
    MovieCountryYear: "India, 2020-Current",
    MovieName: "Bajirao Mastani",
    Moviegenre: "Action",
  },
  {
    id: "9",
    MovieCountryYear: "India, 2020-Current",
    MovieName: "Drishyam",
    Moviegenre: "Adventure Thriller",
  },
  {
    id: "10",
    MovieCountryYear: "India, 2020-Current",
    MovieName: "Kabir Singh",
    Moviegenre: "Adventure Action",
  },
  {
    id: "11",
    MovieCountryYear: "Usa, 2016-Current",
    MovieName: "Dunkrik",
    Moviegenre: "Adventure",
  },
  {
    id: "12",
    MovieCountryYear: "India, 2020-Current",
    MovieName: "No Time To Die",
    Moviegenre: "Adventure Action",
  },
  {
    id: "13",
    MovieCountryYear: "Usa, 2019-Current",
    MovieName: "Don't Breathe",
    Moviegenre: "Adventure Thriller",
  },
  {
    id: "14",
    MovieCountryYear: "Usa, 2019-Current",
    MovieName: "Avengers-Endgame",
    Moviegenre: "Action",
  },
  {
    id: "15",
    MovieCountryYear: "India, 2016-Current",
    MovieName: "The Outpost",
    Moviegenre: "Adventure, Action",
  },
  {
    id: "16",
    MovieCountryYear: "Usa, 2016-Current",
    MovieName: "Tedboundry Tapes",
    Moviegenre: "Adventure, Action",
  },
  {
    id: "17",
    MovieCountryYear: "Usa, 2016-Current",
    MovieName: "Sherlock",
    Moviegenre: "Adventure, Action",
  },
  {
    id: "18",
    MovieCountryYear: "India, 2020-Current",
    MovieName: "Live-Telecast",
    Moviegenre: "Action, Adventure, Thriller",
  },
  {
    id: "19",
    MovieCountryYear: "India, 2022-Current",
    MovieName: "The Fame Game",
    Moviegenre: "Action, Adventure",
  },
  {
    id: "20",
    MovieCountryYear: "India, 2019-Current",
    MovieName: "Mirzapur",
    Moviegenre: "Action Adventure",
  },
  {
    id: "21",
    MovieCountryYear: "Japan, 2016-Current",
    MovieName: "Dragoon Bell Z",
    Moviegenre: "Actionr",
  },
  {
    id: "1",
    MovieCountryYear: "Japan, 2017-Current",
    MovieName: "Death Note",
    Moviegenre: "Action",
  },
  {
    id: "1",
    MovieCountryYear: "Japan, 2017-Current",
    MovieName: "One Punch Man",
    Moviegenre: "Action",
  },
  {
    id: "1",
    MovieCountryYear: "Japan, 2018-Current",
    MovieName: "Avatar",
    Moviegenre: "Action",
  },
  {
    id: "1",
    MovieCountryYear: "Japan, 2018-Current",
    MovieName: "Naruto",
    Moviegenre: "Action",
  },
];
