const LatestCard = [
  {
    id: "1",
    Movieimage: "./images/moviecard1.png",
    MovieCountryYear: "Usa, 2016-Current",
    MovieName: "Stranger Things",
    Moviegenre: "Action, Adventure, Horror",
  },
  {
    id: "2",
    Movieimage: "./images/moviecard2.png",
    MovieCountryYear: "Usa, 2016-Current",
    MovieName: "Batman Begin",
    Moviegenre: "Action Thriller",
  },
  {
    id: "3",
    Movieimage: "./images/moviecard3.png",
    MovieCountryYear: "Usa, 2016-Current",
    MovieName: "Spide-Man Into The Spider Verse",
    Moviegenre: "Action Thriller",
  },
  {
    id: "4",
    Movieimage: "./images/moviecard4.png",
    MovieCountryYear: "Usa, 2020",
    MovieName: "Shang-Chi Legend Of The Ten Rign",
    Moviegenre: "Action",
  },
  {
    id: "5",
    Movieimage: "./images/moviecard5.png",
    MovieCountryYear: "Usa, 2021",
    MovieName: "Dune",
    Moviegenre: "Action, Thriller",
  },
];
const Bollywoodcard = [
  {
    id: "6",
    Movieimage: "./images/moviecard6.png",
    MovieCountryYear: "India, 2020",
    MovieName: "Satyamev Jayate",
    Moviegenre: "Action, Adventure",
  },
  {
    id: "7",
    Movieimage: "./images/moviecard7.png",
    MovieCountryYear: "ndia, 2018-Current",
    MovieName: "Raees",
    Moviegenre: "Action Thriller",
  },
  {
    id: "8",
    Movieimage: "./images/moviecard8.png",
    MovieCountryYear: "India, 2020-Current",
    MovieName: "Bajirao Mastani",
    Moviegenre: "Action",
  },
  {
    id: "9",
    Movieimage: "./images/moviecard9.png",
    MovieCountryYear: "India, 2020-Current",
    MovieName: "Drishyam",
    Moviegenre: "Adventure Thriller",
  },
  {
    id: "10",
    Movieimage: "./images/moviecard10.png",
    MovieCountryYear: "India, 2020-Current",
    MovieName: "Kabir Singh",
    Moviegenre: "Adventure Action",
  },
];
const Hollywoodcard = [
  {
    id: "11",
    Movieimage: "./images/moviecard11.png",
    MovieCountryYear: "Usa, 2016-Current",
    MovieName: "Dunkrik",
    Moviegenre: "Adventure",
  },
  {
    id: "12",
    Movieimage: "./images/moviecard12.png",
    MovieCountryYear: "India, 2020-Current",
    MovieName: "No Time To Die",
    Moviegenre: "Adventure Action",
  },
  {
    id: "13",
    Movieimage: "./images/moviecard13.png",
    MovieCountryYear: "Usa, 2019-Current",
    MovieName: "Don't Breathe",
    Moviegenre: "Adventure Thriller",
  },
  {
    id: "14",
    Movieimage: "./images/moviecard14.png",
    MovieCountryYear: "Usa, 2019-Current",
    MovieName: "Avengers-Endgame",
    Moviegenre: "Action",
  },
  {
    id: "15",
    Movieimage: "./images/moviecard15.png",
    MovieCountryYear: "India, 2016-Current",
    MovieName: "The Outpost",
    Moviegenre: "Adventure, Action",
  },
];
const Webseriescard = [
  {
    id: "16",
    Movieimage: "./images/moviecard16.png",
    MovieCountryYear: "Usa, 2016-Current",
    MovieName: "Tedboundry Tapes",
    Moviegenre: "Adventure, Action",
  },
  {
    id: "17",
    Movieimage: "./images/moviecard17.png",
    MovieCountryYear: "Usa, 2016-Current",
    MovieName: "Sherlock",
    Moviegenre: "Adventure, Action",
  },
  {
    id: "18",
    Movieimage: "./images/moviecard18.png",
    MovieCountryYear: "India, 2020-Current",
    MovieName: "Live-Telecast",
    Moviegenre: "Action, Adventure, Thriller",
  },
  {
    id: "19",
    Movieimage: "./images/moviecard19.png",
    MovieCountryYear: "India, 2022-Current",
    MovieName: "The Fame Game",
    Moviegenre: "Action, Adventure",
  },
  {
    id: "20",
    Movieimage: "./images/moviecard20.png",
    MovieCountryYear: "India, 2019-Current",
    MovieName: "Mirzapur",
    Moviegenre: "Action Adventure",
  },
];
const Anime = [
  {
    id: "21",
    Movieimage: "./images/moviecard21.png",
    MovieCountryYear: "Japan, 2016-Current",
    MovieName: "Dragoon Bell Z",
    Moviegenre: "Actionr",
  },
  {
    id: "22",
    Movieimage: "./images/moviecard22.png",
    MovieCountryYear: "Japan, 2017-Current",
    MovieName: "Death Note",
    Moviegenre: "Action",
  },
  {
    id: "23",
    Movieimage: "./images/moviecard23.png",
    MovieCountryYear: "Japan, 2017-Current",
    MovieName: "One Punch Man",
    Moviegenre: "Action",
  },
  {
    id: "24",
    Movieimage: "./images/moviecard24.png",
    MovieCountryYear: "Japan, 2018-Current",
    MovieName: "Avatar",
    Moviegenre: "Action",
  },
  {
    id: "25",
    Movieimage: "./images/moviecard25.png",
    MovieCountryYear: "Japan, 2018-Current",
    MovieName: "Naruto",
    Moviegenre: "Action",
  },
];
